stages:
    - build

build:
  stage: build
  only:
    - master
  script:
    - docker build -t chemsorly/keras-cntk:latest-win-py2-cpu -t chemsorly/keras-cntk:%PROJECT_VERSION%-win-py2-cpu -f .\dockerfiles\keras-cntk-windows-py2-cpu.dockerfile .
    - docker push chemsorly/keras-cntk-windows:%PROJECT_VERSION%-win-py2-cpu
    - docker push chemsorly/keras-cntk-windows:latest-win-py2-cpu

    - docker build -t chemsorly/keras-cntk:latest-ubuntu-py2-cpu -t chemsorly/keras-cntk:%PROJECT_VERSION%-ubuntu-py2-cpu -f .\dockerfiles\keras-cntk-ubuntu-py2-cpu.dockerfile .
    - docker push chemsorly/keras-cntk-windows:%PROJECT_VERSION%-ubuntu-py2-cpu
    - docker push chemsorly/keras-cntk-windows:latest-ubuntu-py2-cpu

after_script:
    - powershell docker rmi $(docker images -aq) -f
