stages:
    - build

build:
  stage: build
  only:
    - master
  script:
    - docker build -t chemsorly/keras-cntk:win-py2-cpu-latest -t chemsorly/keras-cntk:win-py2-cpu-%PROJECT_VERSION% -f .\dockerfiles\keras-cntk-windows-py2-cpu.dockerfile .
    - docker push chemsorly/keras-cntk-windows:win-py2-cpu-latest
    - docker push chemsorly/keras-cntk-windows:win-py2-cpu-%PROJECT_VERSION%

    - docker build -t chemsorly/keras-cntk:ubuntu-py2-cpu-latest -t chemsorly/keras-cntk:ubuntu-py2-cpu-%PROJECT_VERSION% -f .\dockerfiles\keras-cntk-ubuntu-py2-cpu.dockerfile .
    - docker push chemsorly/keras-cntk-windows:ubuntu-py2-cpu-latest
    - docker push chemsorly/keras-cntk-windows:ubuntu-py2-cpu-%PROJECT_VERSION%

after_script:
    - powershell docker rmi $(docker images -aq) -f
