variables:
    ASSETCONTAINER_NAME: "keras-cntk-windows-assets-$CI_BUILD_REF"

stages:
    - build

build:
  stage: build
  only:
    - master
  script:
    - docker build -t chemsorly/keras-cntk-windows:latest -t chemsorly/keras-cntk-windows:%PROJECT_VERSION% -f .\dockerfiles\keras-cntk-windows.dockerfile .
    - docker push chemsorly/keras-cntk-windows:latest
    - docker push chemsorly/keras-cntk-windows:%PROJECT_VERSION%

after_script:
    - docker rm %ASSETCONTAINER_NAME% -f
    - powershell docker rmi $(docker images -aq) -f
